# Generated by Django 5.0.2 on 2024-02-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformationAboutCustomer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price_discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
