# Generated by Django 5.0.2 on 2024-02-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_delete_informationaboutcustomer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationAboutCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='number_of_purchases',
            field=models.IntegerField(default=1),
        ),
    ]
