# Generated by Django 5.0.2 on 2024-02-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_informationaboutcustomer_cart_number_of_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationaboutcustomer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='informationaboutcustomer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='informationaboutcustomer',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='informationaboutcustomer',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
