# Generated by Django 5.0.2 on 2024-02-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_informationaboutcustomer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationaboutcustomer',
            name='slug',
        ),
        migrations.AlterField(
            model_name='informationaboutcustomer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationaboutcustomer',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationaboutcustomer',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
